name: museumguide
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 
  firebase_core: 
  provider: 
  cloud_firestore:
  firebase_auth:
  font_awesome_flutter:
  google_fonts: 
  google_sign_in:
  sign_in_with_apple: 
  crypto: 
  json_annotation:
  rxdart:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: 
  json_serializable:
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon_round.png"

flutter:
  uses-material-design: true
  assets:
  - assets/
  - assets/covers/
  - assets/illustrations/
  - assets/icon/
  - assets/avatars/
  - assets/guide/