// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpIh5AggTydiRaHS1xQJ8MEBA0CeuzF6U',
    appId: '1:460922085051:web:3b6f51eede5fa94dc2d39e',
    messagingSenderId: '460922085051',
    projectId: 'dev-helder-quizapp',
    authDomain: 'dev-helder-quizapp.firebaseapp.com',
    storageBucket: 'dev-helder-quizapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvu9W8ixQcJMdQQ0oVbU1BLWpOazQCtBE',
    appId: '1:460922085051:android:1340f238502bb8aec2d39e',
    messagingSenderId: '460922085051',
    projectId: 'dev-helder-quizapp',
    storageBucket: 'dev-helder-quizapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbroIVir3oDACpbm2pzKtRkBNzp12Aqcg',
    appId: '1:460922085051:ios:c459cca768fcf68fc2d39e',
    messagingSenderId: '460922085051',
    projectId: 'dev-helder-quizapp',
    storageBucket: 'dev-helder-quizapp.appspot.com',
    iosBundleId: 'com.nikitagordeev10.museumguide',
  );
}
