// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJAkhE6CQEKOPGzZ5n3HRncsOypKsdaTA',
    appId: '1:103731987395:web:4a28c2ea5423f059b17376',
    messagingSenderId: '103731987395',
    projectId: 'museumguide-fde28',
    authDomain: 'museumguide-fde28.firebaseapp.com',
    storageBucket: 'museumguide-fde28.appspot.com',
    measurementId: 'G-ZXR976ZCV4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVWiTzbsYoUHLzCzhOIbWWuVbwBUv-3pI',
    appId: '1:103731987395:android:a580634c62c76728b17376',
    messagingSenderId: '103731987395',
    projectId: 'museumguide-fde28',
    storageBucket: 'museumguide-fde28.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuTxHtICFzCY8dE0l2G1Ec7ltXx148ZJY',
    appId: '1:103731987395:ios:1f52bbca155d319cb17376',
    messagingSenderId: '103731987395',
    projectId: 'museumguide-fde28',
    storageBucket: 'museumguide-fde28.appspot.com',
    androidClientId: '103731987395-mjkqfmrg48rpufv5m9em3hivoaqlb82s.apps.googleusercontent.com',
    iosClientId: '103731987395-pc6dvpq1556milq6f6o00spqnlpfvjoc.apps.googleusercontent.com',
    iosBundleId: 'com.nikitagordeev10.museumguide',
  );

}